# Build a Neural Network with Pytorch

Implement a vanilla neural network from scratch using Pytorch.

We will cover the following:

- PyTorch basics

- Build a neural network

- Program your own neural network

# PyTorch basics

In the previous lessons, we looked at some Pytorch code, but this time we will take a closer look at it.

Pytorch (https://pytorch.org/) is an open-source Python deep learning framework that enables us to build and train neural networks. Pytorch is a library that helps you perform mathematical operations between matrices in their basic form because, as you will realize in this course, deep learning is just simple linear algebra.

The fundamental building block of Pytorch is the **tensor**. A tensor is an N-dimensional array. We can have an 1D-array (or a vector) $x=[1,2,3,4,5]$ , a 2D-array $y=[[1,2],[3,4]]$, and so on.

In Pytorch, these can be defined as:

In [ ]:
import torch

X= torch.tensor ([1,2])
Y= torch.tensor ([[1,2],[3,4]])

From there we can define almost all mathematical operations between tensors.

In [ ]:
#Z = torch.add(X,Y)
Z = torch.matmul(X,Y)
Z = 1 / (1+torch.exp(X))

Let’s revisit the neuron’s equation:

> $a = f(w_1 ∗ a_1 + w_2 ∗ a_2 + w_3 ∗ a_3 + b_o)$

The above equation can be easily transformed into tensor operations (remember everything in deep learning can be represented as tensors).

> $[a] = f([ w1, w2, w3] * [a1, a2,a3 ] +[b_o])$

All we did here is this:

- Gather together all activations into a 1-d vector and all weights into another 1-d vector.

- Multiply them.

- Add the bias.

- Apply the sigmoid function in the result

Note that individual numbers can also be seen as 0d tensors.

Let’s proceed with our first exercise. Using everything that you learned just now,try to program your first neuron from scratch. All necessary information and commands have already been mentioned, so all you have to do is reconstruct the above equation using Pytorch.


# Build a neural network

Luckily, for us, Pytorch provides lots of ready functions so that we don’t have to build each neuron from scratch. For example, if we want to declare a layer of neurons, we can use the premade function as follows:

> linear1 = nn.Linear(5, 20)

The above command constructs a layer that inputs a 5-dimensional vector and outputs a 20-dimensional vector.

To develop a neural network, we can use the following function, which defines a sequential order of individual layers:

Using five lines of code, we build a neural network that has two inputs, a hidden layer with three neurons and two outputs. Note that the linear layer does not contain the activation function, so we have to explicitly declare them as well.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        # Define the input layer (for example, 10 input features)
        self.fc1 = nn.Linear(10, 5)  # 5 neurons in the hidden layer
        # Define the output layer (assuming a binary classification)
        self.fc2 = nn.Linear(5, 2)   # 2 output features

    def forward(self, x):
        # Pass the input through the hidden layer, then apply a ReLU activation function
        x = F.relu(self.fc1(x))
        # Pass the result through the output layer
        o = self.fc2(x)
        return o

# Program your own neural network

Now that you are more familiar with building a neural network in Pytorch, let’s see what’s going on under the hood. We will come back to the 2-3-2 NN for simplicity.

The following is another way to define a NN in Pytorch:

In [3]:
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.linear1 = nn.Linear(2, 3)
        self.linear2 = nn.Linear(3, 2)

    def forward(self, x):
        h = torch.sigmoid(self.linear1(x))
        o = torch.sigmoid(self.linear2(h))
        return o

Many people prefer it because it gives more control and explainability over the network. To run a forward propagation, we can create a random input, initialize the model, and pass the input as an argument as follows:

In [4]:
model= Model()
X = torch.randn((1, 2))
Y = model(X)

Our input is:

In [5]:
X

tensor([[ 0.5873, -0.4979]])

While the model’s weights are:

In [6]:
for param in model.parameters():
  print(param.data)

tensor([[-0.2052,  0.6032],
        [-0.6249, -0.4945],
        [ 0.1953, -0.0970]])
tensor([-0.1747, -0.6703, -0.3340])
tensor([[ 0.4929, -0.3548,  0.0806],
        [ 0.2325, -0.0759, -0.3061]])
tensor([-0.1267,  0.5160])


Now, it is your turn to build a neural network. Let’s have it receive a vector with 10 numbers, have 3 linear layers with dimensions 128, 64, 2, and two RELU layers in between.

In [ ]:
import torch
import torch.nn as nn

seed = 172
torch.manual_seed(seed)
torch.cuda.manual_seed(seed)

class myModel(nn.Module):
    def __init__(self):
        ### WRITE YOUR ANSWER HERE

    def forward(self, x):
        ### WRITE YOUR ANSWER HERE

        return o

In [ ]:
our_ann = myModel()

X = torch.randn((1, 10))
Y = our_ann(X)

In [ ]:
for param in our_ann.parameters():
  print(param.data)
  print(param.data.shape)

tensor([[ 0.1817,  0.1289,  0.1198,  ..., -0.3111,  0.1290, -0.0238],
        [ 0.0344, -0.1924,  0.2416,  ..., -0.1691,  0.1559, -0.3137],
        [ 0.0039, -0.0058, -0.2089,  ...,  0.0114, -0.1345,  0.0234],
        ...,
        [ 0.1086,  0.0373,  0.1918,  ...,  0.2507, -0.3046,  0.1682],
        [ 0.1203,  0.1845, -0.2415,  ..., -0.0630, -0.1802, -0.1472],
        [ 0.1200, -0.0621,  0.2880,  ..., -0.2424,  0.2864, -0.0272]])
torch.Size([128, 10])
tensor([[-0.0547, -0.0213,  0.0212,  ...,  0.0614, -0.0597,  0.0626],
        [-0.0222, -0.0509,  0.0137,  ...,  0.0110, -0.0503, -0.0594],
        [ 0.0716, -0.0456, -0.0242,  ..., -0.0191,  0.0055, -0.0498],
        ...,
        [-0.0422,  0.0660,  0.0765,  ..., -0.0261, -0.0673,  0.0115],
        [ 0.0171,  0.0497, -0.0492,  ...,  0.0613,  0.0039,  0.0024],
        [-0.0601,  0.0879,  0.0165,  ...,  0.0848,  0.0207, -0.0804]])
torch.Size([64, 128])
tensor([-0.0097, -0.0150, -0.0699, -0.0042,  0.0336,  0.0414, -0.0097, -0.0540,
        